#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# ... otros comandos de pre-commit ...

# Ejecutar pruebas solo si están especificadas
yarn test || echo "No hay pruebas especificadas, omitiendo..."
